[package]
name = "wdrc_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
futures = "*"
toolforge = { version = "5", features = ["mysql"] }
wikimisc = { git = "https://github.com/magnusmanske/wikimisc.git" }

[profile.release]
opt-level = 3
lto = 'fat'
panic = 'abort'
codegen-units = 1
